server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://139.9.42.255:3306/yami_shops?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Hbjtrl1818!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      # 端口，默认为637 9
      port: 6379
      # 数据库索引
      database: 1
      # 密码
      password: erson@0099
      # 连接超时时间
      timeout: 60s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
logging:
  config: classpath:logback/logback-prod.xml
#xxl-job:
#  accessToken: default_token
#  logPath: /data/applogs/xxl-job/jobhandler
#  admin:
#    addresses: http://localhost:8080/xxl-job-admin
wx:
  mp:
    appid: wxcd8474ae707619bd
  miniapp:
    configs:
      - appid: wxc9c9d062867d8bb2 #微信小程序的appid
        secret: 9bb91ff47c681cfca608d5819d63f9e8 #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
