server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://139.9.42.255:3306/yami_shops?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Hbjtrl1818!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: 139.9.42.255
      port: 6379
      database: 1
logging:
  config: classpath:logback/logback-prod.xml
#xxl-job:
#  accessToken: default_token
#  logPath: /data/applogs/xxl-job/jobhandler
#  admin:
#    addresses: http://localhost:8080/xxl-job-admin
wx:
  mp:
    appid: wxcd8474ae707619bd
  miniapp:
    configs:
      - appid: wxc9c9d062867d8bb2 #微信小程序的appid
        secret: 9bb91ff47c681cfca608d5819d63f9e8 #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
